language: python
python:
  - "2.7"
# command to install dependencies
install:
- "pip install --upgrade pip"
- "pip install -r requirements.txt"
before_script:
- python /tests/unittest_data/test_file_downloader.py
# command to run tests
script:
- python -m unittest discover
